### PR TITLE
add missing tags

### PR DESCRIPTION
**Pull request by FinalAngel**
We also need to add h5 to h6 for completion

### CODE REVIEW

**Comment by vxsx** [comment]
do you think we should add `header` and `footer` for good measure?

**Comment by FinalAngel** [comment]
had the discussion also with @christianbertschy I'm not completely opposed to it but also neither in favor :D I think we could add them for completion @vxsx ?

**Comment by christianbertschy** [comment]
I'm all for adding +1:

**Comment by mkoistinen** [comment]
+1 from me, but remember, these are just the defaults. The developer will (hopefully) override as appropriate.

**Comment by mkoistinen** [comment]
Don't forget to update the readme file.

**Pull request merged**
